apiVersion: v2
name: kubeopencode
description: A Kubernetes-native system for executing AI agent tasks across multiple repositories
type: application
version: 0.0.4
appVersion: "v0.0.4"
keywords:
  - automation
  - ai-agent
  - batch-processing
  - kubernetes-native
maintainers:
  - name: KubeOpenCode Team
home: https://github.com/kubeopencode/kubeopencode
sources:
  - https://github.com/kubeopencode/kubeopencode
